
This module is prepared for  SOCIAL MEDIA MINING MADE EASY: PYTHON TEXT ANALYTICS CRASH COURSE WORKSHOP, 25-26 September 2023.

Author: Dr Lailatul Qadri Zakaria, Asian Language Processing Lab (ASLAN), Center For Artificial Intelligence Technology (CAIT), Faculty of Information Science and Technology (FTSM), Universiti Kebangsaan Malaysia (UKM).

Email: lailatul.qadri@ukm.edu.my

#Tweety
Previously, numerous Python libraries that did not utilise Twitter's API could be used for Twitter data scraping, however owing to changes in Twitter policy, most of the libraries are no longer usable.

In this workshop, I will use **Tweepy** library to extract Twitter data. Tweepy is can be used to extract data such as get user info, get tweets, searching tweets based on keywords, get trends, get community and get community tweets.

Let's go!

Resource for Tweety documentation link: https://mahrtayyab.github.io/tweety_docs/#

## Install required library

### 1. We need to install tweety library using the following code:

In [ ]:
!pip install tweety-ns

Requirement already satisfied: tweety-ns in /usr/local/lib/python3.10/dist-packages (1.1.7)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from tweety-ns) (4.12.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (from tweety-ns) (3.1.3)
Requirement already satisfied: httpx in /usr/local/lib/python3.10/dist-packages (from tweety-ns) (0.27.0)
Requirement already satisfied: dateutils in /usr/local/lib/python3.10/dist-packages (from tweety-ns) (0.6.12)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->tweety-ns) (2.5)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from dateutils->tweety-ns) (2.8.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from dateutils->tweety-ns) (2023.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns) (2024.6.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns) (1.0.5)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns) (3.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx->tweety-ns) (0.14.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl->tweety-ns) (1.1.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->tweety-ns) (1.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil->dateutils->tweety-ns) (1.16.0)

### 2. Upgrade the library to the latest version:

In [ ]:
!pip install https://github.com/mahrtayyab/tweety/archive/main.zip --upgrade

Collecting https://github.com/mahrtayyab/tweety/archive/main.zip
  Using cached https://github.com/mahrtayyab/tweety/archive/main.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from tweety-ns==1.1.7) (4.12.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (from tweety-ns==1.1.7) (3.1.3)
Requirement already satisfied: httpx in /usr/local/lib/python3.10/dist-packages (from tweety-ns==1.1.7) (0.27.0)
Requirement already satisfied: dateutils in /usr/local/lib/python3.10/dist-packages (from tweety-ns==1.1.7) (0.6.12)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->tweety-ns==1.1.7) (2.5)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from dateutils->tweety-ns==1.1.7) (2.8.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from dateutils->tweety-ns==1.1.7) (2023.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns==1.1.7) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns==1.1.7) (2024.6.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns==1.1.7) (1.0.5)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns==1.1.7) (3.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx->tweety-ns==1.1.7) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx->tweety-ns==1.1.7) (0.14.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl->tweety-ns==1.1.7) (1.1.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->tweety-ns==1.1.7) (1.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil->dateutils->tweety-ns==1.1.7) (1.16.0)

## Tweety Functions

**Note:** If you have a Twitter account, you may use your Twitter ID and password to access more Tweepy features. Otherwise, your Tweety access is restricted to the first two functions.


**Basic Functions:**

a.   Get User Info

b.   Get User's Tweet (limited to 100 tweets)

**Advance Functions:**

a.   Get User Info (similar to basic function)

b.   Get User's Tweet (more than 100 tweets)

c.   Searching a keyword

In [ ]:
!pip install tweety

Requirement already satisfied: tweety in /usr/local/lib/python3.10/dist-packages (0.1.6)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from tweety) (4.12.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from tweety) (2.0.3)
Requirement already satisfied: selenium in /usr/local/lib/python3.10/dist-packages (from tweety) (4.21.0)
Requirement already satisfied: spacy in /usr/local/lib/python3.10/dist-packages (from tweety) (3.7.4)
Requirement already satisfied: vaderSentiment in /usr/local/lib/python3.10/dist-packages (from tweety) (3.3.2)
Requirement already satisfied: textblob in /usr/local/lib/python3.10/dist-packages (from tweety) (0.17.1)
Requirement already satisfied: chromedriver-binary==74.0.3729.6.0 in /usr/local/lib/python3.10/dist-packages (from tweety) (74.0.3729.6.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->tweety) (2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->tweety) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->tweety) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->tweety) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->tweety) (1.25.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from selenium->tweety) (2.0.7)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.10/dist-packages (from selenium->tweety) (0.25.1)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.10/dist-packages (from selenium->tweety) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.10/dist-packages (from selenium->tweety) (2024.6.2)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from selenium->tweety) (4.12.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (8.2.3)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (0.9.4)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (4.66.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (2.7.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (24.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy->tweety) (3.4.0)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.10/dist-packages (from textblob->tweety) (3.8.1)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy->tweety) (1.2.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob->tweety) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob->tweety) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob->tweety) (2024.5.15)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->tweety) (0.7.0)
Requirement already satisfied: pydantic-core==2.18.4 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->tweety) (2.18.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->tweety) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy->tweety) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy->tweety) (3.7)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy->tweety) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy->tweety) (0.1.5)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->tweety) (23.2.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->tweety) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->tweety) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->tweety) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium->tweety) (1.2.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.10/dist-packages (from trio-websocket~=0.9->selenium->tweety) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium->tweety) (1.7.1)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.4.0,>=0.1.0->spacy->tweety) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy->tweety) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy->tweety) (1.1.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium->tweety) (0.14.0)

In [ ]:
from tweety import Twitter
app = Twitter("session")

### 1. Basic Function (no sign-in required)

#### a.  Get User info
Lets try to search for a public figure in Twitter. In this example, I will search for our former prime minister - Tun Dr Mahathir Mohamad. You will need his twitter name to get his information: "chedetofficial".

In [ ]:
user = app.get_user_info('omarsuleiman504')
print(user)

User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True)

Now, try to get other user information by changing the user name. You also can search for your user information.

In [ ]:
#user = app.get_user_info('ADD USER NAME HERE!')
#print(user)

#### b. Get tweets from the user (limited to 100 tweets)
You now have the user information. Next, let's see if we can capture what they tweet. In this example, I would like to extract Tun M' tweets and save it into pandas.

In [ ]:
# Importing pandas as pd
import pandas as pd

After running this code, you will receive raw tweet data from Tun M. It comprises a lot of information, like the Tweet id, author, username, and produced data. Observe the output:
*   Without Twitter User ID and password, you only can access 100 tweet from the user.
*   Tweet's date are random

In [ ]:
all_tweets = app.get_tweets("omarsuleiman504")

tweet_text = [] # we want to store tweet's text
tweet_date = [] # we want to store tweet's date

for tweet in all_tweets:
      print(tweet)
      tweet_text.append(tweet.text)
      tweet_date.append(tweet.date)

Tweet(id=1714335831375102257, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-17 17:41:27+00:00)
Tweet(id=1794852404070084732, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-05-26 22:05:34+00:00)
Tweet(id=1746321133270343695, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-13 23:59:37+00:00)
Tweet(id=1601622769925779459, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2022-12-10 16:59:59+00:00)
Tweet(id=1745820470153236852, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-12 14:50:10+00:00)
Tweet(id=1718023007783051530, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-27 21:52:59+00:00)
Tweet(id=1758184895673700680, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-02-15 17:41:59+00:00)
Tweet(id=1747298284052389973, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-16 16:42:28+00:00)
Tweet(id=1719334660017094871, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-31 12:45:01+00:00)
Tweet(id=1712191022485131487, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-11 19:38:45+00:00)
Tweet(id=1714096187257815202, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-17 01:49:12+00:00)
Tweet(id=1714354840686473564, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-17 18:56:59+00:00)
Tweet(id=1715136197566025841, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-19 22:41:49+00:00)
Tweet(id=1711524141193703759, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-09 23:28:48+00:00)
Tweet(id=1795032944970481712, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-05-27 10:02:58+00:00)
Tweet(id=1717043337683751371, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-25 05:00:07+00:00)
Tweet(id=1713660539765743642, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-15 20:58:05+00:00)
Tweet(id=1720895002102972578, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-04 20:05:15+00:00)
Tweet(id=1785711929991782762, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-05-01 16:44:35+00:00)
Tweet(id=1712103690008396064, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-11 13:51:43+00:00)
Tweet(id=1712279819205873714, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-12 01:31:36+00:00)
Tweet(id=1756900054139297992, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-02-12 04:36:29+00:00)
Tweet(id=1714298477935542354, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-17 15:13:01+00:00)
Tweet(id=1736153597594022190, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-16 22:37:28+00:00)
Tweet(id=1720464796867301507, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-03 15:35:46+00:00)
Tweet(id=1715186796194082824, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-20 02:02:53+00:00)
Tweet(id=1715738735982059576, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-21 14:36:06+00:00)
Tweet(id=1721970497393480020, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-07 19:18:53+00:00)
Tweet(id=1721676884474204523, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-06 23:52:11+00:00)
Tweet(id=1726220736195633152, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-19 12:47:49+00:00)
Tweet(id=1714721742168428918, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-18 19:14:55+00:00)
Tweet(id=1716225295932375145, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-22 22:49:31+00:00)
Tweet(id=1747394963829059763, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-16 23:06:39+00:00)
Tweet(id=1717950347157934541, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-27 17:04:15+00:00)
Tweet(id=1735666986221178934, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-15 14:23:51+00:00)
Tweet(id=1643413313114497025, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-04-05 00:40:41+00:00)
Tweet(id=1724854502073770424, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-15 18:18:54+00:00)
Tweet(id=1715950468160012633, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-22 04:37:27+00:00)
Tweet(id=1712874558921883917, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-13 16:54:53+00:00)
Tweet(id=1744789153093505288, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-09 18:32:05+00:00)
Tweet(id=1714432635907268730, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-18 00:06:07+00:00)
Tweet(id=1774955697949544783, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-04-02 00:23:10+00:00)
Tweet(id=1745596936529268888, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-12 00:01:55+00:00)
Tweet(id=1713186697523961945, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-14 13:35:12+00:00)
Tweet(id=1745249829884674305, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-11 01:02:39+00:00)
Tweet(id=1711787301452284101, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-10 16:54:30+00:00)
Tweet(id=1712488896481648841, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-12 15:22:24+00:00)
Tweet(id=1731793321461178419, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-04 21:51:17+00:00)
Tweet(id=1713709350173196511, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-16 00:12:02+00:00)
Tweet(id=1768432638866378827, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-03-15 00:22:51+00:00)
Tweet(id=1717608921219613032, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-26 18:27:33+00:00)
Tweet(id=1716828433291096154, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-24 14:46:10+00:00)
Tweet(id=1713197727855653134, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-14 14:19:02+00:00)
Tweet(id=1712682729798512787, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-13 04:12:37+00:00)
Tweet(id=1750181218178453681, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-24 15:38:13+00:00)
Tweet(id=1713336018802200798, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-14 23:28:33+00:00)
Tweet(id=1713563664744141177, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-15 14:33:08+00:00)
Tweet(id=1716947098636312890, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-24 22:37:42+00:00)
Tweet(id=1726077465200607536, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-19 03:18:31+00:00)
Tweet(id=1740793377338380727, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-29 17:54:18+00:00)
Tweet(id=1723182918871216547, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-11 03:36:37+00:00)
Tweet(id=1745442975126086105, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-11 13:50:08+00:00)
Tweet(id=1790908404753461395, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-05-16 00:53:31+00:00)
Tweet(id=1759974414911778988, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-02-20 16:12:53+00:00)
Tweet(id=1751253831130746894, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-27 14:40:24+00:00)
Tweet(id=1749915754714079551, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-23 22:03:22+00:00)
Tweet(id=1649489195591778305, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-04-21 19:04:04+00:00)
Tweet(id=1726312857740919155, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-19 18:53:53+00:00)
Tweet(id=1719113895665668354, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-30 22:07:46+00:00)
Tweet(id=1757024367135834560, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-02-12 12:50:27+00:00)
Tweet(id=1724658204775260521, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-15 05:18:53+00:00)
Tweet(id=1740558500650979711, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-29 02:20:59+00:00)
Tweet(id=1731431159412724004, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-03 21:52:11+00:00)
Tweet(id=1715562185974231392, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-21 02:54:33+00:00)
Tweet(id=1718604387038163446, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-29 12:23:10+00:00)
Tweet(id=1717570798611775823, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-26 15:56:03+00:00)
Tweet(id=1720084210952917092, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-02 14:23:28+00:00)
Tweet(id=1731134794669449245, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-03 02:14:32+00:00)
Tweet(id=1713055264788697372, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-14 04:52:56+00:00)
Tweet(id=1711814094011990402, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-10 18:40:58+00:00)
Tweet(id=1738377778955993190, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-23 01:55:34+00:00)
Tweet(id=1757478656698470872, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-02-13 18:55:38+00:00)
Tweet(id=1729192583145070622, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-27 17:36:53+00:00)
Tweet(id=1743983089947213962, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-07 13:09:04+00:00)
Tweet(id=1732852731684020441, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-07 20:01:00+00:00)
Tweet(id=1736424788971696337, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-17 16:35:05+00:00)
Tweet(id=1742637604971917448, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-03 20:02:36+00:00)
Tweet(id=1722780801958281231, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-10 00:58:45+00:00)
Tweet(id=1724436556201550274, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-14 14:38:08+00:00)
Tweet(id=1725502761511350774, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-11-17 13:14:51+00:00)
Tweet(id=1713940631209333184, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-10-16 15:31:04+00:00)
Tweet(id=1746300980109427093, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2024-01-13 22:39:33+00:00)
Tweet(id=1655930950520385536, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-05-09 13:41:18+00:00)
Tweet(id=1739353988326170762, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-25 18:34:41+00:00)
Tweet(id=1733127076843032830, author=User(id=776528756, username=omarsuleiman504, name=Dr. Omar Suleiman, verified=True), created_on=2023-12-08 14:11:09+00:00)

In [ ]:
# Calling DataFrame constructor on list

df = pd.DataFrame({'Date': tweet_date, 'Tweet':tweet_text})
df

,Date,Tweet
0,2023-10-17 17:41:27+00:00,"Dear world,\n\nIsrael just bombed a Christian ..."
1,2024-05-26 22:05:34+00:00,Be honest America: What does this remind you of?
2,2024-01-13 23:59:37+00:00,"400,000 people in DC today. The largest Palest..."
3,2022-12-10 16:59:59+00:00,Yesssss!\n\nMashaAllah Morocco making Africa p...
4,2024-01-12 14:50:10+00:00,Apartheid will fall.\n🇿🇦 🇵🇸 https://t.co/nVlXW...
...,...,...
90,2023-10-16 15:31:04+00:00,Protests around the world have been larger tha...
91,2024-01-13 22:39:33+00:00,"If you are blind to our humanity, we are not b..."
92,2023-05-09 13:41:18+00:00,Making lots of dua for Pakistan 🇵🇰 right now. ...
93,2023-12-25 18:34:41+00:00,You did this @POTUS
94,2023-12-08 14:11:09+00:00,Evil. https://t.co/pGI2OvmFoa

Save your data in the form of csv

In [ ]:
df.to_csv("omarsuleiman504.csv")

**Limitation:** Without Twitter User ID and password, you only can access 100 tweet from the user.

### 2. Advance Functions (sign-in required)
In order to use advance functions, you need to provide Twitter user ID, password and extra password. The extra password will be emailed to you based on your Twitter ID email.

app.sign_in("USER ID", "PASSWORD", extra="EXTRA PASSWORD")

#### a. Get tweets from the user


Let us now attempt to extract Tun M's tweets. We may also set the "pages" value. If "pages" is set to 1, it will retrieve 20 tweets per page. Increase the value of "pages" to extract more tweets.

In [ ]:
#app.sign_in("qadri_laila", "XXXXX")

In [ ]:
app.sign_in("useranakwa69579", "useranakwatan@01", extra="cfzgtaxp")
target_username = "omarsuleiman504"
user = app.get_user_info(target_username)
all_tweets = app.get_tweets(user, pages = 20)

tweet_date = []
tweet_text = []

# Iterate over the tweets
for tweet in all_tweets:
    # Check if tweet is a dictionary and has the required keys
    if isinstance(tweet, dict):
        tweet_date.append(tweet.get('created_on'))  # Use the appropriate key for the date
        tweet_text.append(tweet.get('text'))  # Use the appropriate key for the text

# Print the results
print("Tweet Dates:", tweet_date)
print("Tweet Texts:", tweet_text)

Tweet Dates: [datetime.datetime(2024, 6, 9, 16, 32, 58, tzinfo=tzlocal()), datetime.datetime(2024, 6, 9, 12, 35, 40, tzinfo=tzlocal()), datetime.datetime(2024, 6, 9, 12, 35, 5, tzinfo=tzlocal()), datetime.datetime(2024, 6, 9, 12, 31, 45, tzinfo=tzlocal()), datetime.datetime(2024, 6, 9, 0, 25, 46, tzinfo=tzlocal()), datetime.datetime(2024, 6, 8, 19, 23, 47, tzinfo=tzlocal()), datetime.datetime(2024, 6, 8, 19, 21, 48, tzinfo=tzlocal()), datetime.datetime(2024, 6, 8, 16, 3, 12, tzinfo=tzlocal()), datetime.datetime(2024, 6, 7, 21, 6, 26, tzinfo=tzlocal()), datetime.datetime(2024, 6, 7, 21, 3, 22, tzinfo=tzlocal()), None, datetime.datetime(2024, 6, 7, 15, 36, 44, tzinfo=tzlocal()), datetime.datetime(2024, 6, 6, 19, 59, 45, tzinfo=tzlocal()), datetime.datetime(2024, 6, 6, 15, 9, 45, tzinfo=tzlocal()), datetime.datetime(2024, 6, 6, 2, 12, 25, tzinfo=tzlocal()), datetime.datetime(2024, 6, 5, 20, 29, 20, tzinfo=tzlocal()), datetime.datetime(2024, 6, 5, 16, 11, 46, tzinfo=tzlocal()), datetime.datetime(2024, 6, 5, 3, 1, 10, tzinfo=tzlocal()), datetime.datetime(2024, 6, 4, 17, 24, 43, tzinfo=tzlocal()), datetime.datetime(2024, 6, 4, 4, 55, 59, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 23, 30, 43, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 20, 51, 3, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 18, 38, 6, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 16, 58, 32, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 13, 54, 12, tzinfo=tzlocal()), datetime.datetime(2024, 6, 2, 22, 24, 15, tzinfo=tzlocal()), datetime.datetime(2024, 6, 2, 20, 43, 56, tzinfo=tzlocal()), datetime.datetime(2024, 6, 2, 10, 20, 12, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 22, 7, 51, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 16, 34, 22, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 4, 29, 12, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 4, 28, 46, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 4, 19, 42, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 31, 21, 44, 21, tzinfo=tzlocal()), datetime.datetime(2024, 5, 31, 15, 46, tzinfo=tzlocal()), datetime.datetime(2024, 5, 31, 6, 13, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 31, 4, 5, 43, tzinfo=tzlocal()), datetime.datetime(2024, 5, 30, 22, 7, 21, tzinfo=tzlocal()), datetime.datetime(2024, 5, 30, 19, 18, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 30, 15, 0, 48, tzinfo=tzlocal()), datetime.datetime(2024, 5, 29, 18, 52, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 29, 15, 11, 54, tzinfo=tzlocal()), datetime.datetime(2024, 5, 29, 12, 2, 2, tzinfo=tzlocal()), datetime.datetime(2024, 5, 29, 4, 53, 19, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 22, 59, 18, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 19, 11, 6, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 17, 26, 59, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 3, 26, 50, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 1, 29, 51, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 20, 52, 1, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 10, 2, 58, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 9, 56, 41, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 9, 51, 45, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 9, 50, 55, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 3, 2, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 26, 22, 5, 34, tzinfo=tzlocal()), datetime.datetime(2024, 5, 26, 17, 24, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 26, 3, 48, 56, tzinfo=tzlocal()), datetime.datetime(2024, 5, 26, 3, 18, 58, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 19, 52, 22, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 17, 30, 26, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 17, 20, 26, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 17, 19, 17, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 5, 32, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 24, 18, 7, 25, tzinfo=tzlocal()), datetime.datetime(2024, 5, 24, 16, 14, 11, tzinfo=tzlocal()), datetime.datetime(2024, 5, 24, 14, 12, 13, tzinfo=tzlocal()), datetime.datetime(2024, 5, 24, 0, 30, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 23, 29, 19, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 22, 37, 59, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 19, 8, 40, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 18, 27, 39, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 16, 3, 54, tzinfo=tzlocal()), datetime.datetime(2024, 5, 22, 5, 33, 55, tzinfo=tzlocal()), datetime.datetime(2024, 5, 22, 5, 4, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 22, 0, 55, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 23, 22, 9, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 23, 14, 22, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 22, 57, 8, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 22, 55, 24, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 18, 40, 14, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 17, 36, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 16, 12, 11, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 16, 12, 6, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 16, 11, 57, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 16, 10, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 3, 28, 54, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 1, 50, 32, tzinfo=tzlocal()), datetime.datetime(2024, 5, 20, 19, 38, 29, tzinfo=tzlocal()), datetime.datetime(2024, 5, 20, 3, 23, 58, tzinfo=tzlocal()), datetime.datetime(2024, 5, 20, 2, 0, 31, tzinfo=tzlocal()), datetime.datetime(2024, 5, 19, 15, 54, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 18, 20, 43, 8, tzinfo=tzlocal()), datetime.datetime(2024, 5, 18, 15, 44, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 18, 3, 39, 13, tzinfo=tzlocal()), datetime.datetime(2024, 5, 18, 1, 18, 36, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 17, 17, 28, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 17, 15, 41, 12, tzinfo=tzlocal()), datetime.datetime(2024, 5, 17, 15, 19, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 17, 1, 26, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 16, 22, 8, 48, tzinfo=tzlocal()), datetime.datetime(2024, 5, 16, 22, 8, 46, tzinfo=tzlocal()), datetime.datetime(2024, 5, 16, 21, 6, 14, tzinfo=tzlocal()), datetime.datetime(2024, 5, 16, 0, 53, 31, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 23, 18, 54, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 23, 13, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 15, 56, 45, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 15, 56, 32, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 11, 55, 41, tzinfo=tzlocal()), datetime.datetime(2024, 5, 14, 22, 21, 1, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 14, 20, 6, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 14, 20, 5, 57, tzinfo=tzlocal()), datetime.datetime(2024, 5, 14, 20, 5, 36, tzinfo=tzlocal()), datetime.datetime(2024, 5, 14, 14, 53, 8, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 23, 28, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 22, 1, 47, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 13, 19, 15, 3, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 19, 14, 40, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 18, 43, 17, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 15, 42, 1, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 12, 3, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 6, 6, 36, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 6, 6, 24, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 13, 0, 48, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 11, 2, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 11, 0, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 10, 4, 43, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 9, 55, 16, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 5, 16, 17, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 4, 58, 6, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 4, 58, 2, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 2, 31, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 0, 33, 31, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 0, 33, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 22, 13, 38, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 22, 13, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 11, 23, 21, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 6, 2, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 4, 32, 26, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 10, 23, 57, 28, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 19, 27, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 18, 7, 31, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 18, 3, 25, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 13, 53, 39, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 5, 35, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 4, 20, 9, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 0, 55, 12, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 0, 54, 11, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 23, 41, 2, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 17, 17, 12, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 15, 30, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 5, 22, 26, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 5, 14, 3, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 1, 6, 34, tzinfo=tzlocal()), datetime.datetime(2024, 5, 8, 19, 32, 52, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 8, 11, 14, 50, tzinfo=tzlocal()), datetime.datetime(2024, 5, 8, 11, 11, 15, tzinfo=tzlocal()), datetime.datetime(2024, 5, 8, 2, 45, tzinfo=tzlocal()), datetime.datetime(2024, 5, 7, 20, 22, 11, tzinfo=tzlocal()), datetime.datetime(2024, 5, 7, 17, 51, 43, tzinfo=tzlocal()), datetime.datetime(2024, 5, 7, 17, 43, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 7, 15, 6, 34, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 22, 28, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 22, 2, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 19, 28, 28, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 16, 3, 28, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 8, 42, 3, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 5, 22, 57, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 1, 47, 40, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 1, 43, 41, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 1, 43, 30, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 1, 42, 36, tzinfo=tzlocal()), datetime.datetime(2024, 5, 5, 19, 26, 56, tzinfo=tzlocal()), datetime.datetime(2024, 5, 5, 18, 15, 28, tzinfo=tzlocal()), datetime.datetime(2024, 5, 5, 12, 9, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 4, 23, 31, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 4, 15, 27, 57, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 3, 18, 22, 1, tzinfo=tzlocal()), datetime.datetime(2024, 5, 3, 12, 47, 34, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 2, 23, 7, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 21, 28, 56, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 18, 7, 32, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 16, 32, 30, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 16, 21, 41, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 16, 21, 13, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 14, 35, 52, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 2, 28, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 1, 7, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 23, 17, 9, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 17, 3, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 16, 44, 35, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 16, 33, 57, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 31, 36, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 24, 58, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 24, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 23, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 23, 38, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 22, 29, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 11, 10, 21, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 4, 53, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 4, 13, 46, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 4, 3, 53, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 23, 41, 12, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 23, 34, 20, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 23, 18, 7, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 18, 17, 7, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 16, 40, 8, tzinfo=tzlocal()), datetime.datetime(2024, 4, 29, 23, 12, 37, tzinfo=tzlocal()), datetime.datetime(2024, 4, 29, 22, 35, 20, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 29, 3, 3, 41, tzinfo=tzlocal()), datetime.datetime(2024, 4, 28, 16, 42, 34, tzinfo=tzlocal()), datetime.datetime(2024, 4, 27, 19, 32, 52, tzinfo=tzlocal()), datetime.datetime(2024, 4, 27, 16, 44, 31, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 26, 13, 0, tzinfo=tzlocal()), datetime.datetime(2024, 4, 26, 12, 56, 25, tzinfo=tzlocal()), datetime.datetime(2024, 4, 25, 22, 37, 53, tzinfo=tzlocal()), datetime.datetime(2024, 4, 25, 18, 54, 26, tzinfo=tzlocal()), datetime.datetime(2024, 4, 25, 10, 22, 7, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 25, 0, 46, 6, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 21, 59, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 14, 17, 8, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 14, 15, 39, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 5, 0, 17, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 4, 30, 2, tzinfo=tzlocal()), datetime.datetime(2024, 4, 23, 19, 59, 42, tzinfo=tzlocal()), datetime.datetime(2024, 4, 23, 12, 35, 10, tzinfo=tzlocal()), datetime.datetime(2024, 4, 23, 12, 34, 28, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 22, 17, 47, 28, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 17, 41, 7, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 17, 24, 54, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 17, 24, 46, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 17, 6, 31, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 16, 47, 39, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 15, 43, 23, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 14, 24, 57, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 14, 23, 19, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 13, 59, 51, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 13, 59, 50, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 13, 48, 27, tzinfo=tzlocal()), datetime.datetime(2024, 4, 21, 23, 49, 49, tzinfo=tzlocal()), datetime.datetime(2024, 4, 21, 17, 45, 9, tzinfo=tzlocal()), datetime.datetime(2024, 4, 21, 14, 15, 26, tzinfo=tzlocal()), datetime.datetime(2024, 4, 21, 6, 47, 22, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 18, 40, 53, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 13, 56, 48, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 13, 55, 31, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 13, 49, 48, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 3, 32, 51, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 19, 5, 22, 32, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 22, 15, 33, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 18, 55, 6, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 18, 12, 4, 22, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 11, 58, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 5, 59, 35, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 5, 27, 23, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 18, 4, 27, 42, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 3, 54, 23, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 0, 24, 28, tzinfo=tzlocal()), datetime.datetime(2024, 4, 17, 16, 59, 21, tzinfo=tzlocal()), datetime.datetime(2024, 4, 17, 4, 4, 45, tzinfo=tzlocal()), datetime.datetime(2024, 4, 17, 4, 4, 40, tzinfo=tzlocal()), datetime.datetime(2024, 4, 17, 1, 44, 55, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 22, 4, 21, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 19, 46, 45, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 12, 43, 51, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 10, 29, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 10, 28, 7, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 10, 26, 14, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 15, 20, 40, 48, tzinfo=tzlocal()), datetime.datetime(2024, 4, 15, 13, 2, 46, tzinfo=tzlocal()), datetime.datetime(2024, 4, 15, 1, 3, 51, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 14, 32, 33, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 13, 41, 42, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 6, 3, 47, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 4, 39, 3, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 2, 36, 4, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 21, 57, 8, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 21, 55, 55, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 15, 20, 28, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 15, 9, 46, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 9, 8, 44, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 2, 30, 35, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 2, 6, 14, tzinfo=tzlocal()), datetime.datetime(2024, 4, 12, 12, 54, 56, tzinfo=tzlocal()), datetime.datetime(2024, 4, 12, 6, 10, 16, tzinfo=tzlocal()), datetime.datetime(2024, 4, 12, 4, 28, 13, tzinfo=tzlocal()), datetime.datetime(2024, 4, 11, 9, 38, 55, tzinfo=tzlocal()), datetime.datetime(2024, 4, 11, 3, 10, 31, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 17, 7, 55, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 1, 29, 54, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 1, 28, 45, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 1, 28, 37, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 1, 28, 34, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 18, 30, 58, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 8, 41, 2, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 1, 40, 23, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 1, 25, 11, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 0, 24, 13, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 0, 23, 58, tzinfo=tzlocal()), datetime.datetime(2024, 4, 8, 1, 23, 34, tzinfo=tzlocal()), datetime.datetime(2024, 4, 8, 0, 31, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 8, 0, 30, 50, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 22, 4, 27, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 20, 4, 6, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 11, 56, 25, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 11, 56, 17, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 11, 55, 58, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 9, 28, 10, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 6, 23, 3, 57, tzinfo=tzlocal()), datetime.datetime(2024, 4, 6, 18, 35, tzinfo=tzlocal()), datetime.datetime(2024, 4, 6, 9, 53, 37, tzinfo=tzlocal()), datetime.datetime(2024, 4, 6, 0, 10, 19, tzinfo=tzlocal()), datetime.datetime(2024, 4, 5, 20, 21, 58, tzinfo=tzlocal()), datetime.datetime(2024, 4, 5, 1, 17, 13, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 23, 40, 37, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 21, 11, 14, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 12, 8, 12, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 12, 7, 52, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 10, 4, 51, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 9, 59, 36, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 9, 58, 29, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 5, 43, 25, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 23, 36, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 22, 38, 50, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 22, 16, 23, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 22, 16, 12, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 19, 46, 33, tzinfo=tzlocal()), datetime.datetime(20

In [ ]:
# Calling DataFrame constructor on list

df = pd.DataFrame({'Date': tweet_date, 'Tweet':tweet_text})
df

,Date,Tweet
0,2024-06-09 16:32:58+00:00,When Musa (as) was lost and abandoned in the d...
1,2024-06-09 12:35:40+00:00,Heart-stopping moment: A father places his son...
2,2024-06-09 12:35:05+00:00,274 Palestinians killed in a bloody massacre t...
3,2024-06-09 12:31:45+00:00,From inside of the Riyadul-Jannah (One of the ...
4,2024-06-09 00:25:46+00:00,Palestinian deaths do not matter to you. Our c...
...,...,...
356,2024-04-01 17:38:07+00:00,Our sins negatively affect the ummah just as o...
357,2024-04-01 12:31:53+00:00,⚠️ Graphic content ⚠️\n\nPhotos showing the re...
358,2024-04-01 12:29:34+00:00,"I’m sorry humans, but this is what has been do..."
359,2024-04-01 11:00:53+00:00,لعنة الله على الظالمين
360,2024-04-01 03:26:21+00:00,Relinquish your grudges. Revive your heart. Re...

In [ ]:
df.to_csv("my_data_omarsuleiman504.csv")

#### b. Searching a keyword
Do you have a specific topic or subject that you want to collect from Twitter? We can use searching a keyword function to get them. In order to search tweets, you need to provide such information:

*   keywords : example #UKM, paracetamol, pulau redang, etc..
*   nunmber of Tweet pages you want to get
*   Filter (optional) : Filter you would like to apply on the search.
*   Wait time: Number of seconds to wait between multiple requests

In this case, we'd want to get tweets on Fukushima water waste. As we all know, Japan began dumping treated radioactive water into the Pacific Ocean from the stricken Fukushima nuclear power plant. To obtain the information, we must first find relevant terms, such as "fukushima waste water" or "fukushima radiation water." Each query will get different results.

**Note:** Don't worry if you get Error 500 when looking for data. It is only a momentary issue that indicates "Something is broken. This is generally a transitory mistake, such as when a server is under heavy load or an endpoint is experiencing problems". Grab a coffee and after a few minutes try again with a lower page number.

In [ ]:
from tweety.filters import SearchFilters

#tweets = app.search("#SPM2021", pages = 20, filter_=SearchFilters.Latest(), wait_time = 2)

#tweet_text = []
#tweet_date = []
#for tweet in tweets:
  #tweet_text.append(tweet.text)
  #tweet_date.append(tweet.date)

#df = pd.DataFrame({'Date': tweet_date, 'Tweet':tweet_text})
#df

In this example, I'll name my file my_data.csv. You may change the file's name accordingly.

In [ ]:
df.to_csv("my_data_omarsuleiman504.csv")

We also can filter/search for users by using user name. In this example, we search for

##**Self Activity: Collect Data From Twitter**
Now, you can collect your own social media data.

1. You may use the given template to collect your own dataset based on Twitter user

In [ ]:
app.sign_in("useranakwa69579", "useranakwatan@01", extra="cfzgtaxp")
target_username = "omarsuleiman504"
user = app.get_user_info(target_username)
all_tweets = app.get_tweets(user, pages = 20)

tweet_date = []
tweet_text = []

# Iterate over the tweets
for tweet in all_tweets:
    # Check if tweet is a dictionary and has the required keys
    if isinstance(tweet, dict):
        tweet_date.append(tweet.get('created_on'))  # Use the appropriate key for the date
        tweet_text.append(tweet.get('text'))  # Use the appropriate key for the text

# Print the results
print("Tweet Dates:", tweet_date)
print("Tweet Texts:", tweet_text)

# Calling DataFrame constructor on list
df = pd.DataFrame({'Date': tweet_date, 'Tweet':tweet_text})
df

#save the data in csv format
df.to_csv("my_data_omarsuleiman504.csv", index=False)

Tweet Dates: [datetime.datetime(2024, 6, 9, 16, 32, 58, tzinfo=tzlocal()), datetime.datetime(2024, 6, 9, 12, 35, 40, tzinfo=tzlocal()), datetime.datetime(2024, 6, 9, 12, 35, 5, tzinfo=tzlocal()), datetime.datetime(2024, 6, 9, 12, 31, 45, tzinfo=tzlocal()), datetime.datetime(2024, 6, 9, 0, 25, 46, tzinfo=tzlocal()), datetime.datetime(2024, 6, 8, 19, 23, 47, tzinfo=tzlocal()), datetime.datetime(2024, 6, 8, 19, 21, 48, tzinfo=tzlocal()), datetime.datetime(2024, 6, 8, 16, 3, 12, tzinfo=tzlocal()), datetime.datetime(2024, 6, 7, 21, 6, 26, tzinfo=tzlocal()), datetime.datetime(2024, 6, 7, 21, 3, 22, tzinfo=tzlocal()), None, datetime.datetime(2024, 6, 7, 15, 36, 44, tzinfo=tzlocal()), datetime.datetime(2024, 6, 6, 19, 59, 45, tzinfo=tzlocal()), datetime.datetime(2024, 6, 6, 15, 9, 45, tzinfo=tzlocal()), datetime.datetime(2024, 6, 6, 2, 12, 25, tzinfo=tzlocal()), datetime.datetime(2024, 6, 5, 20, 29, 20, tzinfo=tzlocal()), datetime.datetime(2024, 6, 5, 16, 11, 46, tzinfo=tzlocal()), datetime.datetime(2024, 6, 5, 3, 1, 10, tzinfo=tzlocal()), datetime.datetime(2024, 6, 4, 17, 24, 43, tzinfo=tzlocal()), datetime.datetime(2024, 6, 4, 4, 55, 59, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 23, 30, 43, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 20, 51, 3, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 18, 38, 6, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 16, 58, 32, tzinfo=tzlocal()), datetime.datetime(2024, 6, 3, 13, 54, 12, tzinfo=tzlocal()), datetime.datetime(2024, 6, 2, 22, 24, 15, tzinfo=tzlocal()), datetime.datetime(2024, 6, 2, 20, 43, 56, tzinfo=tzlocal()), datetime.datetime(2024, 6, 2, 10, 20, 12, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 22, 7, 51, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 16, 34, 22, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 4, 29, 12, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 4, 28, 46, tzinfo=tzlocal()), datetime.datetime(2024, 6, 1, 4, 19, 42, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 31, 21, 44, 21, tzinfo=tzlocal()), datetime.datetime(2024, 5, 31, 15, 46, tzinfo=tzlocal()), datetime.datetime(2024, 5, 31, 6, 13, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 31, 4, 5, 43, tzinfo=tzlocal()), datetime.datetime(2024, 5, 30, 22, 7, 21, tzinfo=tzlocal()), datetime.datetime(2024, 5, 30, 19, 18, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 30, 15, 0, 48, tzinfo=tzlocal()), datetime.datetime(2024, 5, 29, 18, 52, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 29, 15, 11, 54, tzinfo=tzlocal()), datetime.datetime(2024, 5, 29, 12, 2, 2, tzinfo=tzlocal()), datetime.datetime(2024, 5, 29, 4, 53, 19, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 22, 59, 18, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 19, 11, 6, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 17, 26, 59, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 3, 26, 50, tzinfo=tzlocal()), datetime.datetime(2024, 5, 28, 1, 29, 51, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 20, 52, 1, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 10, 2, 58, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 9, 56, 41, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 9, 51, 45, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 9, 50, 55, tzinfo=tzlocal()), datetime.datetime(2024, 5, 27, 3, 2, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 26, 22, 5, 34, tzinfo=tzlocal()), datetime.datetime(2024, 5, 26, 17, 24, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 26, 3, 48, 56, tzinfo=tzlocal()), datetime.datetime(2024, 5, 26, 3, 18, 58, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 19, 52, 22, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 17, 30, 26, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 17, 20, 26, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 17, 19, 17, tzinfo=tzlocal()), datetime.datetime(2024, 5, 25, 5, 32, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 24, 18, 7, 25, tzinfo=tzlocal()), datetime.datetime(2024, 5, 24, 16, 14, 11, tzinfo=tzlocal()), datetime.datetime(2024, 5, 24, 14, 12, 13, tzinfo=tzlocal()), datetime.datetime(2024, 5, 24, 0, 30, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 23, 29, 19, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 22, 37, 59, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 19, 8, 40, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 18, 27, 39, tzinfo=tzlocal()), datetime.datetime(2024, 5, 23, 16, 3, 54, tzinfo=tzlocal()), datetime.datetime(2024, 5, 22, 5, 33, 55, tzinfo=tzlocal()), datetime.datetime(2024, 5, 22, 5, 4, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 22, 0, 55, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 23, 22, 9, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 23, 14, 22, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 22, 57, 8, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 22, 55, 24, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 18, 40, 14, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 17, 36, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 16, 12, 11, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 16, 12, 6, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 16, 11, 57, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 16, 10, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 3, 28, 54, tzinfo=tzlocal()), datetime.datetime(2024, 5, 21, 1, 50, 32, tzinfo=tzlocal()), datetime.datetime(2024, 5, 20, 19, 38, 29, tzinfo=tzlocal()), datetime.datetime(2024, 5, 20, 3, 23, 58, tzinfo=tzlocal()), datetime.datetime(2024, 5, 20, 2, 0, 31, tzinfo=tzlocal()), datetime.datetime(2024, 5, 19, 15, 54, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 18, 20, 43, 8, tzinfo=tzlocal()), datetime.datetime(2024, 5, 18, 15, 44, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 18, 3, 39, 13, tzinfo=tzlocal()), datetime.datetime(2024, 5, 18, 1, 18, 36, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 17, 17, 28, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 17, 15, 41, 12, tzinfo=tzlocal()), datetime.datetime(2024, 5, 17, 15, 19, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 17, 1, 26, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 16, 22, 8, 48, tzinfo=tzlocal()), datetime.datetime(2024, 5, 16, 22, 8, 46, tzinfo=tzlocal()), datetime.datetime(2024, 5, 16, 21, 6, 14, tzinfo=tzlocal()), datetime.datetime(2024, 5, 16, 0, 53, 31, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 23, 18, 54, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 23, 13, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 15, 56, 45, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 15, 56, 32, tzinfo=tzlocal()), datetime.datetime(2024, 5, 15, 11, 55, 41, tzinfo=tzlocal()), datetime.datetime(2024, 5, 14, 22, 21, 1, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 14, 20, 6, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 14, 20, 5, 57, tzinfo=tzlocal()), datetime.datetime(2024, 5, 14, 20, 5, 36, tzinfo=tzlocal()), datetime.datetime(2024, 5, 14, 14, 53, 8, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 23, 28, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 22, 1, 47, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 13, 19, 15, 3, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 19, 14, 40, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 18, 43, 17, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 15, 42, 1, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 12, 3, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 6, 6, 36, tzinfo=tzlocal()), datetime.datetime(2024, 5, 13, 6, 6, 24, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 13, 0, 48, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 11, 2, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 11, 0, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 10, 4, 43, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 9, 55, 16, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 5, 16, 17, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 4, 58, 6, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 4, 58, 2, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 2, 31, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 0, 33, 31, tzinfo=tzlocal()), datetime.datetime(2024, 5, 12, 0, 33, 4, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 22, 13, 38, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 22, 13, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 11, 23, 21, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 6, 2, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 11, 4, 32, 26, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 10, 23, 57, 28, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 19, 27, 23, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 18, 7, 31, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 18, 3, 25, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 13, 53, 39, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 5, 35, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 4, 20, 9, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 0, 55, 12, tzinfo=tzlocal()), datetime.datetime(2024, 5, 10, 0, 54, 11, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 23, 41, 2, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 17, 17, 12, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 15, 30, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 5, 22, 26, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 5, 14, 3, tzinfo=tzlocal()), datetime.datetime(2024, 5, 9, 1, 6, 34, tzinfo=tzlocal()), datetime.datetime(2024, 5, 8, 19, 32, 52, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 8, 11, 14, 50, tzinfo=tzlocal()), datetime.datetime(2024, 5, 8, 11, 11, 15, tzinfo=tzlocal()), datetime.datetime(2024, 5, 8, 2, 45, tzinfo=tzlocal()), datetime.datetime(2024, 5, 7, 20, 22, 11, tzinfo=tzlocal()), datetime.datetime(2024, 5, 7, 17, 51, 43, tzinfo=tzlocal()), datetime.datetime(2024, 5, 7, 17, 43, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 7, 15, 6, 34, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 22, 28, 33, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 22, 2, 53, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 19, 28, 28, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 16, 3, 28, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 8, 42, 3, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 5, 22, 57, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 1, 47, 40, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 1, 43, 41, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 1, 43, 30, tzinfo=tzlocal()), datetime.datetime(2024, 5, 6, 1, 42, 36, tzinfo=tzlocal()), datetime.datetime(2024, 5, 5, 19, 26, 56, tzinfo=tzlocal()), datetime.datetime(2024, 5, 5, 18, 15, 28, tzinfo=tzlocal()), datetime.datetime(2024, 5, 5, 12, 9, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 4, 23, 31, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 4, 15, 27, 57, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 3, 18, 22, 1, tzinfo=tzlocal()), datetime.datetime(2024, 5, 3, 12, 47, 34, tzinfo=tzlocal()), None, datetime.datetime(2024, 5, 2, 23, 7, 27, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 21, 28, 56, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 18, 7, 32, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 16, 32, 30, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 16, 21, 41, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 16, 21, 13, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 14, 35, 52, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 2, 28, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 2, 1, 7, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 23, 17, 9, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 17, 3, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 16, 44, 35, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 16, 33, 57, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 31, 36, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 24, 58, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 24, 20, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 23, 42, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 23, 38, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 13, 22, 29, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 11, 10, 21, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 4, 53, 5, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 4, 13, 46, tzinfo=tzlocal()), datetime.datetime(2024, 5, 1, 4, 3, 53, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 23, 41, 12, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 23, 34, 20, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 23, 18, 7, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 18, 17, 7, tzinfo=tzlocal()), datetime.datetime(2024, 4, 30, 16, 40, 8, tzinfo=tzlocal()), datetime.datetime(2024, 4, 29, 23, 12, 37, tzinfo=tzlocal()), datetime.datetime(2024, 4, 29, 22, 35, 20, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 29, 3, 3, 41, tzinfo=tzlocal()), datetime.datetime(2024, 4, 28, 16, 42, 34, tzinfo=tzlocal()), datetime.datetime(2024, 4, 27, 19, 32, 52, tzinfo=tzlocal()), datetime.datetime(2024, 4, 27, 16, 44, 31, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 26, 13, 0, tzinfo=tzlocal()), datetime.datetime(2024, 4, 26, 12, 56, 25, tzinfo=tzlocal()), datetime.datetime(2024, 4, 25, 22, 37, 53, tzinfo=tzlocal()), datetime.datetime(2024, 4, 25, 18, 54, 26, tzinfo=tzlocal()), datetime.datetime(2024, 4, 25, 10, 22, 7, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 25, 0, 46, 6, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 21, 59, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 14, 17, 8, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 14, 15, 39, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 5, 0, 17, tzinfo=tzlocal()), datetime.datetime(2024, 4, 24, 4, 30, 2, tzinfo=tzlocal()), datetime.datetime(2024, 4, 23, 19, 59, 42, tzinfo=tzlocal()), datetime.datetime(2024, 4, 23, 12, 35, 10, tzinfo=tzlocal()), datetime.datetime(2024, 4, 23, 12, 34, 28, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 22, 17, 47, 28, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 17, 41, 7, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 17, 24, 54, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 17, 24, 46, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 17, 6, 31, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 16, 47, 39, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 15, 43, 23, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 14, 24, 57, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 14, 23, 19, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 13, 59, 51, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 13, 59, 50, tzinfo=tzlocal()), datetime.datetime(2024, 4, 22, 13, 48, 27, tzinfo=tzlocal()), datetime.datetime(2024, 4, 21, 23, 49, 49, tzinfo=tzlocal()), datetime.datetime(2024, 4, 21, 17, 45, 9, tzinfo=tzlocal()), datetime.datetime(2024, 4, 21, 14, 15, 26, tzinfo=tzlocal()), datetime.datetime(2024, 4, 21, 6, 47, 22, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 18, 40, 53, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 13, 56, 48, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 13, 55, 31, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 13, 49, 48, tzinfo=tzlocal()), datetime.datetime(2024, 4, 20, 3, 32, 51, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 19, 5, 22, 32, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 22, 15, 33, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 18, 55, 6, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 18, 12, 4, 22, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 11, 58, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 5, 59, 35, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 5, 27, 23, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 18, 4, 27, 42, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 3, 54, 23, tzinfo=tzlocal()), datetime.datetime(2024, 4, 18, 0, 24, 28, tzinfo=tzlocal()), datetime.datetime(2024, 4, 17, 16, 59, 21, tzinfo=tzlocal()), datetime.datetime(2024, 4, 17, 4, 4, 45, tzinfo=tzlocal()), datetime.datetime(2024, 4, 17, 4, 4, 40, tzinfo=tzlocal()), datetime.datetime(2024, 4, 17, 1, 44, 55, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 22, 4, 21, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 19, 46, 45, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 12, 43, 51, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 10, 29, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 10, 28, 7, tzinfo=tzlocal()), datetime.datetime(2024, 4, 16, 10, 26, 14, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 15, 20, 40, 48, tzinfo=tzlocal()), datetime.datetime(2024, 4, 15, 13, 2, 46, tzinfo=tzlocal()), datetime.datetime(2024, 4, 15, 1, 3, 51, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 14, 32, 33, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 13, 41, 42, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 6, 3, 47, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 4, 39, 3, tzinfo=tzlocal()), datetime.datetime(2024, 4, 14, 2, 36, 4, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 21, 57, 8, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 21, 55, 55, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 15, 20, 28, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 15, 9, 46, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 9, 8, 44, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 2, 30, 35, tzinfo=tzlocal()), datetime.datetime(2024, 4, 13, 2, 6, 14, tzinfo=tzlocal()), datetime.datetime(2024, 4, 12, 12, 54, 56, tzinfo=tzlocal()), datetime.datetime(2024, 4, 12, 6, 10, 16, tzinfo=tzlocal()), datetime.datetime(2024, 4, 12, 4, 28, 13, tzinfo=tzlocal()), datetime.datetime(2024, 4, 11, 9, 38, 55, tzinfo=tzlocal()), datetime.datetime(2024, 4, 11, 3, 10, 31, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 17, 7, 55, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 1, 29, 54, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 1, 28, 45, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 1, 28, 37, tzinfo=tzlocal()), datetime.datetime(2024, 4, 10, 1, 28, 34, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 18, 30, 58, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 8, 41, 2, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 1, 40, 23, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 1, 25, 11, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 0, 24, 13, tzinfo=tzlocal()), datetime.datetime(2024, 4, 9, 0, 23, 58, tzinfo=tzlocal()), datetime.datetime(2024, 4, 8, 1, 23, 34, tzinfo=tzlocal()), datetime.datetime(2024, 4, 8, 0, 31, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 8, 0, 30, 50, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 22, 4, 27, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 20, 4, 6, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 11, 56, 25, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 11, 56, 17, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 11, 55, 58, tzinfo=tzlocal()), datetime.datetime(2024, 4, 7, 9, 28, 10, tzinfo=tzlocal()), None, datetime.datetime(2024, 4, 6, 23, 3, 57, tzinfo=tzlocal()), datetime.datetime(2024, 4, 6, 18, 35, tzinfo=tzlocal()), datetime.datetime(2024, 4, 6, 9, 53, 37, tzinfo=tzlocal()), datetime.datetime(2024, 4, 6, 0, 10, 19, tzinfo=tzlocal()), datetime.datetime(2024, 4, 5, 20, 21, 58, tzinfo=tzlocal()), datetime.datetime(2024, 4, 5, 1, 17, 13, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 23, 40, 37, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 21, 11, 14, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 12, 8, 12, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 12, 7, 52, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 10, 4, 51, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 9, 59, 36, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 9, 58, 29, tzinfo=tzlocal()), datetime.datetime(2024, 4, 4, 5, 43, 25, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 23, 36, 24, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 22, 38, 50, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 22, 16, 23, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 22, 16, 12, tzinfo=tzlocal()), datetime.datetime(2024, 4, 3, 19, 46, 33, tzinfo=tzlocal()), datetime.datetime(20

2. Search for any topic of your interest.

In [ ]:
tweets = app.search("Rafah", pages = 20, filter_=SearchFilters.Latest(), wait_time = 10)

tweet_text = []
tweet_date = []
for tweet in tweets:
  tweet_text.append(tweet.text)
  tweet_date.append(tweet.date)

df = pd.DataFrame({'Date': tweet_date, 'Tweet':tweet_text})

#save the data in csv format
df.to_csv("Rafah.csv", index=False) # you may change the data name accordingly.